artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/Varsanrecp/End-to-End-Book-Recommendation-System/raw/refs/heads/main/book%20dataset.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data
